masters:
  hosts:
    master1:
      ansible_host: 192.168.0.10 
      ansible_user: c0dr 
      ansible_python_interpreter: /usr/bin/python3
  
workers:
  hosts:
    node1:
      ansible_host: 192.168.0.11 
      ansible_user: c0dr 
      ansible_python_interpreter: /usr/bin/python3
    node2:
      ansible_host: 192.168.0.12
      ansible_user: c0dr
      ansible_python_interpreter: /usr/bin/python3
    node3:
      ansible_host: 192.168.0.13
      ansible_user: c0dr
      ansible_python_interpreter: /usr/bin/python3