# Oscar A. Carrera
# 09/28/2019
---
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" --apiserver-cert-extra-sans="{{ ansible_default_ipv4.address }}"  --node-name {{ansible_hostname}} --pod-network-cidr={{ kubernetes_cidr }} --ignore-preflight-errors=all
  become: true

- name: Create the kube directory
  file:
    path: ~/.kube
    state: directory
  become: false

- name: Copy the kube config file
  shell:
    cmd: cat /etc/kubernetes/admin.conf >> ~/.kube/config
  become: true

- name: Install calico pod network
  become: false 
  command: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml
  become: true

- name: Allow pod scheduling in master node
  become: false
  command: kubectl taint nodes --all node-role.kubernetes.io/master-
  become: true

- name: Copy the kube config file again..
  shell:
    cmd: cat /etc/kubernetes/admin.conf >> ~/.kube/config
  become: true